# Generated by Django 4.2.7 on 2024-03-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebooklink', models.URLField(blank=True, null=True)),
                ('twitterlink', models.URLField(blank=True, null=True)),
                ('instagramlink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='Socialmedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socialmedia', to='web.socialmedia'),
        ),
    ]
