# Generated by Django 4.2.7 on 2024-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_socialmedia_doctors_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='facebooklink',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='instagramlink',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='twitterlink',
            new_name='twitter_link',
        ),
    ]
